apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-new
  namespace: nightjob
  labels:
    app: be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: appjarcont
          image: stephin2020/kubernetes-django-nightjob:1.0.3
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: "mysql"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: password
            - name: DATABASE_PORT
              value: "3306"
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: websvc
  namespace: nightjob
  annotations:
    metallb.universe.tf/address-pool: gnc-stephen-ip
spec:
  type: LoadBalancer
  selector:
    app: be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
