---
kind: "Service"
apiVersion: "v1"
metadata:
  name: "mysql"
  namespace: "nightjob"
spec:
  ports:
    -
      name: "mysql"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "mysql"
  namespace: "nightjob"
subsets:
  -
    addresses:
      -
        ip: "192.168.0.239"
    ports:
      -
        port: 3306
        name: "mysql"
