# Generated by Django 3.0.4 on 2020-03-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='operation',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='operation',
            name='vendor_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
